{
    'name': 'doctor',
    'version': '1.0',
    'category': 'General',
    'summary': 'Módulo para processamento e gerenciamento das informações referentes ao ProDoctor',
    'author': ['Marcelo Barbosa dos Santos'],
    'depends': ['base'],
    'data': [
        'data\especialidade.xml',
        'data\convenios.xml',
        'data\\usuarios.xml',
        'data\cirurgias.xml',
        'data\procedimentos.xml',
        'views\doctor_view.xml',
        'views\pacientes_contas_procedimentos_view.xml',
        'views\convenios_view.xml',
        'views\\regras_view.xml',
        'views\especificas_view.xml',
        'views\\raiox_view.xml',
        'views\especialidade_view.xml',
        'views\cirurgias_view.xml',
        'views\\usuarios_view.xml',
        'views\cirurgia_view.xml',
        'views\procedimentos_view.xml',
        'views\procedimento_view.xml',
        'views\consulta_view.xml',
        # 'views\\relatorio_doctor.xml',
    ],
    'installable': True,
    'application': True,
}
